name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_word_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Show date
        run: |
          date
      - name: Show directory content
        run: |
          ls -l