name: Periodic Health Check

on:
  schedule:
    - cron: '* * */3 * *'
  push:
    branches:
      - master

jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check deployed service
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://fso-pokedex-majkel.herokuapp.com/health
          max-attempts: 3
          retry-delay: 30s